apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: weather-deployment
  name: weather-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather-deployment
  template:
    metadata:
      labels:
        app: weather-deployment
    spec:
      containers:
      - image: igfred/weatherapp
        name: weatherapp
        ports:
          - containerPort: 3000

---
##the service: This part exposes the image to the external world

apiVersion: v1
kind: Service
metadata:
  name: weather-svc
  labels:
    app: weather-deployment
spec:
  type: NodePort
  selector:
    app: weather-deployment
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30009

